version: '3.9'
services:
#  rust-dev:
#    build: .
#    container_name: rust_dev_env
#    volumes:
#      - .:/usr/src/app
#    ports:
#      - "8080:8080"
#    command: [ "cargo", "watch", "-x", "run" ]
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: axumate
      POSTGRES_USER: axumate
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - axumate-postgres-data:/var/lib/postgresql/data/

volumes:
  axumate-postgres-data: